#!/bin/bash

# Define version
MYSQLD_EXPORTER_VERSION="0.15.1"

# MySQL configuration
MYSQL_USER="gagan"
MYSQL_PASSWORD="pass@123"
MYSQL_EXPORTER_CONFIG="/etc/.mysqld_exporter.cnf"

# Download mysqld_exporter
wget https://github.com/prometheus/mysqld_exporter/releases/download/v0.15.1/mysqld_exporter-0.15.1.linux-amd64.tar.gz

# Extract mysqld_exporter
tar -xvf mysqld_exporter-${MYSQLD_EXPORTER_VERSION}.linux-amd64.tar.gz

# Move mysqld_exporter binary
sudo mv mysqld_exporter-${MYSQLD_EXPORTER_VERSION}.linux-amd64/mysqld_exporter /usr/local/bin/


# Create MySQL exporter configuration file
cat <<EOF | sudo tee $MYSQL_EXPORTER_CONFIG
[client]
user=$MYSQL_USER
password=$MYSQL_PASSWORD
host=192.168.146.133
EOF

# set the ownership
sudo chown root:prometheus $MYSQL_EXPORTER_CONFIG

# Set permissions for MySQL exporter configuration file
sudo chmod 600 $MYSQL_EXPORTER_CONFIG

# Reload systemd daemon
sudo systemctl daemon-reload


#Configuration file 
cat <<'EOF' | sudo tee /etc/systemd/system/mysqld_exporter.service
[Unit]
Description=Prometheus MySQL Exporter
After=network.target
User=prometheus
Group=prometheus

[Service]
Type=simple
Restart=always
ExecStart=/usr/local/bin/mysqld_exporter \
  --config.my-cnf /etc/.mysqld_exporter.cnf \
  --collect.global_status \
  --collect.info_schema.innodb_metrics \
  --collect.auto_increment.columns \
  --collect.info_schema.processlist \
  --collect.binlog_size \
  --collect.info_schema.tablestats \
  --collect.global_variables \
  --collect.info_schema.query_response_time \
  --collect.info_schema.userstats \
  --collect.info_schema.tables \
  --collect.perf_schema.tablelocks \
  --collect.perf_schema.file_events \
  --collect.perf_schema.eventswaits \
  --collect.perf_schema.indexiowaits \
  --collect.perf_schema.tableiowaits \
  --collect.slave_status \
  --web.listen-address=192.168.146.133:9104

[Install]
WantedBy=multi-user.target
EOF

#start to run daemon-reload
sudo systemctl daemon-reload

# Start mysqld_exporter service
sudo systemctl start mysqld_exporter

# Enable mysqld_exporter service to start on boot
sudo systemctl enable mysqld_exporter

# Configure mysqld_exporter in prometheus.yml
cat <<EOF | sudo tee -a /etc/prometheus/prometheus.yml

  - job_name: "mysql_exporter"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["192.168.146.133:9104"]  # assuming mysqld_exporter is running on ipaddress:9104
EOF

# Restart Prometheus.service
sudo systemctl restart Prometheus.service

# Clean up
rm -rf mysqld_exporter-${MYSQLD_EXPORTER_VERSION}.linux-amd64.tar.gz mysqld_exporter-${MYSQLD_EXPORTER_VERSION}.linux-amd64

echo "mysqld_exporter has been installed and started successfully."
